#配置datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_oa?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    check-process-definitions: false #关闭自动部署

#配置包别名
mybatis:
  type-aliases-package: com.test.pojo

#更改日志级别
logging:
  level:
    #    root: debug
    root: info

#配置pagehelper的被监听方言
pagehelper:
  helper-dialect: mysql


activiti:
#  check-process-definitions: false # activti是否自动部署
#  db-identity-used: true #是否使用activti自带的用户体系
  database-schema-update: true #是否每次都更新数据库







